name: Run Tests on Commit

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests json unittest

    - name: Run tests
      run: python3 TestingDocker.py spliceai_controlBABY.csv
